### ISSUE TITLE
pifacercd.service disabled by default...

### ISSUE THREAD

**Issue by dl9sec** [bobrathbone/piradio#6]
I did a clean install of piRadio step by step from the "Contructors Manual" (13.03.2017) for v5.9.
I followed the instructions at page 46ff and page 79ff concerning the IR stuff.
Unfortunately the RC doesn't work anymore after a reboot.
I checked if the pifacercd service was running, but it did't. It seems, that the service was installed, but disabled.
So i had to enable the systemd-service for pifacercd by doing a
"sudo systemctl enable /lib/systemd/system/pifacercd.service".
After that, the service starts well after each boot. So i think the Constructors Manual should be updated...

**Comment by bobrathbone** [comment]
I will accept this as a bug fix in version 5.10 but will add a note to the manual.
